/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package KalkulatorBMIBMR;

import javax.swing.JOptionPane;

/**
 *
 * @author Ai Najwa
 */
public class NewJFrame extends javax.swing.JFrame {

        public NewJFrame() {
        initComponents();
    }    

    private String getGender() {
        if (jRadioMan.isSelected()) {
            return "Laki-laki";
        } else if (jRadioWoman.isSelected()) {
            return "Perempuan";
        } else {
            return "";
        }
    }

public double calculateBMI(String gender, int age, double weight, double height) {

    // Hitung indeks massa tubuh
    double bmi = weight / (height * height);

    // Konversi indeks massa tubuh ke satuan kg/m^2
    bmi = bmi * 10000;

    // Tentukan kategori BMI
    String category;
    if (gender.equals("Laki-laki")) {
        if (bmi < 18.5) {
            category = "kurus";
        } else if (bmi < 24.9) {
            category = "normal";
        } else if (bmi < 29.9) {
            category = "kegemukan tingkat I";
        } else if (bmi < 34.9) {
            category = "kegemukan tingkat II";
        } else {
            category = "kegemukan tingkat III";
        }
    } else {
        if (bmi < 18.5) {
            category = "kurus";
        } else if (bmi < 22.9) {
            category = "kormal";
        } else if (bmi < 29.9) {
            category = "kegemukan tingkat I";
        } else if (bmi < 34.9) {
            category = "kegemukan tingkat II";
        } else {
            category = "kegemukan tingkat III";
        }
    }

    // Kembalikan nilai BMI dan kategorinya
    return bmi;
}

    
    private double calculateBMR(String gender, int age, double weight, double height) {
    double bmr = 0;

    if (gender.equals("Laki-laki")) {
        bmr = 66.5 + (13.7 * weight) + (5.0 * height) - (6.8 * age);
    } else if (gender.equals("Perempuan")) {
        bmr = 655 + (9.6 * weight) + (1.8 * height) - (4.7 * age);
    }

    return bmr;
}
    // Tambahkan variabel baru untuk menyimpan kisaran berat badan
    private double[] weightRange;

    // Tambahkan method baru untuk menghitung kisaran berat badan
    private double[] calculateWeightRange(double height) {
    // Definisikan nilai minimum dan maksimum kisaran berat badan
    double minWeight = 0;
    double maxWeight = 0;

    // Hitung berat badan minimum dan maksimum
    minWeight = 18.5 * ((height / 100) * (height / 100));
    maxWeight = 23.0 * ((height / 100) * (height / 100));

    // Buat array untuk menyimpan kisaran berat badan
    weightRange = new double[2];

    // Masukkan nilai minimum dan maksimum kisaran berat badan ke dalam array
    weightRange[0] = minWeight;
    weightRange[1] = maxWeight;
    // Kembalikan array kisaran berat badan
    return weightRange;
}
    
    /**
     * Creates new form NewJFrame
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelGender = new javax.swing.JLabel();
        jLabelAge = new javax.swing.JLabel();
        jLabelHeight = new javax.swing.JLabel();
        jLabelWeight = new javax.swing.JLabel();
        jRadioMan = new javax.swing.JRadioButton();
        jRadioWoman = new javax.swing.JRadioButton();
        jTextFieldAge = new javax.swing.JTextField();
        jTextFieldWeight = new javax.swing.JTextField();
        jTextFieldHeight = new javax.swing.JTextField();
        jButtonHitung = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabelBMI = new javax.swing.JLabel();
        jLabelBMR = new javax.swing.JLabel();
        jLabelCategory = new javax.swing.JLabel();
        jLabelWeightRange = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(134, 182, 246));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Kalkulator BMI-BMR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(120, 120, 120))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );

        jPanel2.setBackground(new java.awt.Color(180, 212, 255));

        jLabelGender.setForeground(new java.awt.Color(0, 0, 0));
        jLabelGender.setText("Apa jenis kelamin Anda?");

        jLabelAge.setForeground(new java.awt.Color(0, 0, 0));
        jLabelAge.setText("Berapa usia Anda? (tahun)");

        jLabelHeight.setForeground(new java.awt.Color(0, 0, 0));
        jLabelHeight.setText("Berapa tinggi Anda? (cm)");

        jLabelWeight.setForeground(new java.awt.Color(0, 0, 0));
        jLabelWeight.setText("Berapa berat badan Anda? (kg)");

        jRadioMan.setForeground(new java.awt.Color(0, 0, 0));
        jRadioMan.setText("Laki-laki");

        jRadioWoman.setForeground(new java.awt.Color(0, 0, 0));
        jRadioWoman.setText("Perempuan");

        jTextFieldAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAgeActionPerformed(evt);
            }
        });

        jTextFieldWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldWeightActionPerformed(evt);
            }
        });

        jTextFieldHeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHeightActionPerformed(evt);
            }
        });

        jButtonHitung.setText("Hitung");
        jButtonHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHitungActionPerformed(evt);
            }
        });

        jButtonReset.setText("Ulangi");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        jButtonExit.setText("Keluar");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButtonHitung, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelHeight)
                                    .addComponent(jLabelAge))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldAge, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldHeight, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelGender)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioMan)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioWoman))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelWeight)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioMan)
                    .addComponent(jRadioWoman)
                    .addComponent(jLabelGender))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAge))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHeight)
                    .addComponent(jTextFieldHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelWeight))
                .addGap(18, 18, 18)
                .addComponent(jButtonHitung)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonReset)
                    .addComponent(jButtonExit))
                .addGap(22, 22, 22))
        );

        jPanel3.setBackground(new java.awt.Color(134, 182, 246));

        jLabelBMI.setForeground(new java.awt.Color(0, 0, 0));
        jLabelBMI.setText("...");
        jLabelBMI.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jLabelBMIComponentShown(evt);
            }
        });

        jLabelBMR.setForeground(new java.awt.Color(0, 0, 0));
        jLabelBMR.setText("...");

        jLabelCategory.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCategory.setText("...");
        jLabelCategory.setToolTipText("");

        jLabelWeightRange.setForeground(new java.awt.Color(0, 0, 0));
        jLabelWeightRange.setText("...");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Berikut ini adalah hasil kalkulasi BMI dan BMR Anda:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabelWeightRange)
                    .addComponent(jLabelBMR)
                    .addComponent(jLabelBMI)
                    .addComponent(jLabelCategory))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelBMI)
                .addGap(12, 12, 12)
                .addComponent(jLabelCategory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelBMR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelWeightRange)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHitungActionPerformed
        // Ambil nilai dari radio button dan text field
        String gender = getGender();
        // Cek apakah radio button "Laki-laki" dipilih
        if (jRadioMan.isSelected()) {
            // Tetapkan radio button "Perempuan" tidak dipilih
            jRadioWoman.setSelected(false);
        } else if (jRadioWoman.isSelected()) {
            // Tetapkan radio button "Laki-laki" tidak dipilih
            jRadioMan.setSelected(false);
        }
        int age = Integer.parseInt(jTextFieldAge.getText());
        double height = Double.parseDouble(jTextFieldHeight.getText());
        double weight = Double.parseDouble(jTextFieldWeight.getText());

        // Hitung BMI dan BMR
        double bmi = calculateBMI(gender, age, weight, height);
        double bmr = calculateBMR(gender, age, weight, height);
        
        String category;
        if (gender.equals("Laki-laki")) {
            if (bmi < 18.5) {
                category = "kurus";
            } else if (bmi < 24.9) {
                category = "normal";
            } else if (bmi < 29.9) {
                category = "obesitas tingkat I";
            } else if (bmi < 34.9) {
                category = "obesitas tingkat II";
            } else {
                category = "obesitas tingkat III";
            }
        } else {
            if (bmi < 18.5) {
                category = "kurus";
            } else if (bmi < 22.9) {
                category = "normal";
            } else if (bmi < 29.9) {
                category = "obesitas tingkat I";
            } else if (bmi < 34.9) {
                category = "obesitas tingkat II";
            } else {
                category = "obesitas tingkat III";
            }
        }
        
        // Hitung kisaran berat badan
        weightRange = calculateWeightRange(height);        
        
        // Tampilkan hasil pada panel jPanel3
        jLabelBMI.setText("BMI Anda adalah " + String.format("%.2f", bmi));
        jLabelCategory.setText("Kategori berat badan Anda " + category);
        jLabelBMR.setText("BMR Anda adalah " + String.format("%.2f", bmr) + " kcal/hari");
        jLabelWeightRange.setText("Maka rekomendasi berat badan Anda adalah " 
            + String.format("%.2f", weightRange[0]) + " - " + String.format("%.2f", weightRange[1]) + " kg");


        jPanel3.revalidate();
        jPanel3.repaint();
    }//GEN-LAST:event_jButtonHitungActionPerformed

    private void jTextFieldAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAgeActionPerformed
        int age = Integer.parseInt(jTextFieldAge.getText());
        if (age < 0) {
            JOptionPane.showMessageDialog(this, "Usia tidak boleh kurang dari 0.");
        }
    }//GEN-LAST:event_jTextFieldAgeActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        // Setel radio button laki-laki dan perempuan ke tidak dipilih
        jRadioMan.setSelected(false);
        jRadioWoman.setSelected(false);

        // Bersihkan text field
        jTextFieldAge.setText("");
        jTextFieldHeight.setText("");
        jTextFieldWeight.setText("");

        // Hapus hasil dari panel jPanel3
        //jPanel3.removeAll();
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jTextFieldHeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHeightActionPerformed
        // Dapatkan nilai tinggi dari jTextFieldHeight
        String heightText = jTextFieldHeight.getText();
        int height = Integer.parseInt(heightText);

        // Set nilai tinggi dari jPanel
        jPanel2.setSize(jPanel2.getWidth(), height);
    }//GEN-LAST:event_jTextFieldHeightActionPerformed

    private void jTextFieldWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldWeightActionPerformed
        String weightText = jTextFieldWeight.getText();
        int weight = Integer.parseInt(weightText);
        
        jPanel2.setSize(jPanel2.getWidth(), weight);
    }//GEN-LAST:event_jTextFieldWeightActionPerformed

    private void jLabelBMIComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabelBMIComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelBMIComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonHitung;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelAge;
    private javax.swing.JLabel jLabelBMI;
    private javax.swing.JLabel jLabelBMR;
    private javax.swing.JLabel jLabelCategory;
    private javax.swing.JLabel jLabelGender;
    private javax.swing.JLabel jLabelHeight;
    private javax.swing.JLabel jLabelWeight;
    private javax.swing.JLabel jLabelWeightRange;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioMan;
    private javax.swing.JRadioButton jRadioWoman;
    private javax.swing.JTextField jTextFieldAge;
    private javax.swing.JTextField jTextFieldHeight;
    private javax.swing.JTextField jTextFieldWeight;
    // End of variables declaration//GEN-END:variables

}
